---
aws_region: "{{ lookup('file', '../terraform/swarm_cluster/output/aws_region.txt') }}"
aws_profile: "default"
aws_access_key: "{{ lookup('ini', 'aws_access_key_id section={{ aws_profile }} file=~/.aws/credentials  ') }}"
aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section={{ aws_profile }} file=~/.aws/credentials  ') }}"
